"""add analysis_model to digest

Revision ID: 0929390eaedb
Revises: 344820bf77ce
Create Date: 2026-04-15 14:22:49.744579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0929390eaedb'
down_revision: Union[str, None] = '344820bf77ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digest', schema=None) as batch_op:
        batch_op.drop_column('analysis_model')

    # ### end Alembic commands ###
