"""add cluster_label to insight

Revision ID: 0d2b1bd6be0a
Revises: 2ce1733cfb3d
Create Date: 2026-04-20 20:16:20.015179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d2b1bd6be0a'
down_revision: Union[str, None] = '2ce1733cfb3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cluster_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_insight_cluster_label'), ['cluster_label'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insight_cluster_label'))
        batch_op.drop_column('cluster_label')

    # ### end Alembic commands ###
