"""add user_id and index project_name

Revision ID: 12a7671a4e5b
Revises: fad81535b677
Create Date: 2026-04-08 14:52:17.114569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '12a7671a4e5b'
down_revision: Union[str, None] = 'fad81535b677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_coding_session_project_name'), ['project_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_coding_session_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coding_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_coding_session_project_name'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
