"""add metadata_json to coding_session

Revision ID: 2d8de3881b72
Revises: e975ab530e44
Create Date: 2026-04-12 20:05:52.613052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d8de3881b72'
down_revision: Union[str, None] = 'e975ab530e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.drop_column('metadata_json')

    # ### end Alembic commands ###
