"""add session daily trend and baseline tables

Revision ID: 32aafc8aa95c
Revises: 99e6e117a8ab
Create Date: 2026-04-13 15:47:47.688032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '32aafc8aa95c'
down_revision: Union[str, None] = '99e6e117a8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_baseline',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('avg_turns', sa.Float(), nullable=False),
    sa.Column('avg_tool_count', sa.Float(), nullable=False),
    sa.Column('avg_read_edit_ratio', sa.Float(), nullable=False),
    sa.Column('avg_edits_without_read_pct', sa.Float(), nullable=False),
    sa.Column('avg_error_rate', sa.Float(), nullable=False),
    sa.Column('avg_duration_ms', sa.Float(), nullable=False),
    sa.Column('avg_user_interrupts_per_1k', sa.Float(), nullable=False),
    sa.Column('tool_distribution_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_baseline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_baseline_project_name'), ['project_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_baseline_user_id'), ['user_id'], unique=False)

    op.create_table('session_daily_trend',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('indexed_count', sa.Integer(), nullable=False),
    sa.Column('analyzed_count', sa.Integer(), nullable=False),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('total_tool_calls', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('avg_read_edit_ratio', sa.Float(), nullable=True),
    sa.Column('avg_edits_without_read_pct', sa.Float(), nullable=True),
    sa.Column('avg_user_interrupts_per_1k', sa.Float(), nullable=True),
    sa.Column('avg_research_mutation_ratio', sa.Float(), nullable=True),
    sa.Column('avg_write_vs_edit_pct', sa.Float(), nullable=True),
    sa.Column('avg_error_rate', sa.Float(), nullable=True),
    sa.Column('avg_session_duration_ms', sa.Float(), nullable=True),
    sa.Column('avg_tool_calls_per_turn', sa.Float(), nullable=True),
    sa.Column('agent_distribution_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_daily_trend', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_daily_trend_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_daily_trend_project_name'), ['project_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_daily_trend_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_daily_trend_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_daily_trend', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_daily_trend_user_id'))
        batch_op.drop_index(batch_op.f('ix_session_daily_trend_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_session_daily_trend_project_name'))
        batch_op.drop_index(batch_op.f('ix_session_daily_trend_date'))

    op.drop_table('session_daily_trend')
    with op.batch_alter_table('session_baseline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_baseline_user_id'))
        batch_op.drop_index(batch_op.f('ix_session_baseline_project_name'))

    op.drop_table('session_baseline')
    # ### end Alembic commands ###
