"""add remaining tier 0 metric columns

Revision ID: 33a79a36ff06
Revises: a2e3bdd34440
Create Date: 2026-04-13 16:24:10.545986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '33a79a36ff06'
down_revision: Union[str, None] = 'a2e3bdd34440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeated_edits_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subagent_spawn_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tokens_per_useful_edit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('context_pressure_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('turn_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tool_calls_per_turn', sa.Float(), nullable=True))
        batch_op.drop_column('user_interrupts_per_1k')
        batch_op.drop_column('reasoning_loops_per_1k')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reasoning_loops_per_1k', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('user_interrupts_per_1k', sa.FLOAT(), nullable=True))
        batch_op.drop_column('tool_calls_per_turn')
        batch_op.drop_column('turn_count')
        batch_op.drop_column('context_pressure_score')
        batch_op.drop_column('tokens_per_useful_edit')
        batch_op.drop_column('subagent_spawn_rate')
        batch_op.drop_column('repeated_edits_count')

    # ### end Alembic commands ###
