"""add estimated_analysis_tokens

Revision ID: 344820bf77ce
Revises: 44eeb44658a6
Create Date: 2026-04-14 09:59:06.613961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '344820bf77ce'
down_revision: Union[str, None] = '44eeb44658a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_analysis_tokens', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.drop_column('estimated_analysis_tokens')

    # ### end Alembic commands ###
