"""remove tier 2 metrics from tier 0 tables

Revision ID: 44eeb44658a6
Revises: 33a79a36ff06
Create Date: 2026-04-13 16:25:37.384876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '44eeb44658a6'
down_revision: Union[str, None] = '33a79a36ff06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_baseline', schema=None) as batch_op:
        batch_op.drop_column('avg_user_interrupts_per_1k')

    with op.batch_alter_table('session_daily_trend', schema=None) as batch_op:
        batch_op.drop_column('avg_user_interrupts_per_1k')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_daily_trend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_user_interrupts_per_1k', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('session_baseline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_user_interrupts_per_1k', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
