"""add quality metrics and indexed status

Revision ID: 99e6e117a8ab
Revises: 2d8de3881b72
Create Date: 2026-04-13 15:40:13.400773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '99e6e117a8ab'
down_revision: Union[str, None] = '2d8de3881b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_edit_ratio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('edits_without_read_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('user_interrupts_per_1k', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('research_mutation_ratio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('write_vs_edit_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reasoning_loops_per_1k', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('error_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('interestingness_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('skip_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.drop_column('skip_reason')
        batch_op.drop_column('interestingness_score')
        batch_op.drop_column('error_rate')
        batch_op.drop_column('reasoning_loops_per_1k')
        batch_op.drop_column('write_vs_edit_pct')
        batch_op.drop_column('research_mutation_ratio')
        batch_op.drop_column('user_interrupts_per_1k')
        batch_op.drop_column('edits_without_read_pct')
        batch_op.drop_column('read_edit_ratio')

    # ### end Alembic commands ###
