"""add missing baseline metric fields

Revision ID: a2e3bdd34440
Revises: 32aafc8aa95c
Create Date: 2026-04-13 15:51:01.704283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2e3bdd34440'
down_revision: Union[str, None] = '32aafc8aa95c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_baseline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_research_mutation_ratio', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('avg_write_vs_edit_pct', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_baseline', schema=None) as batch_op:
        batch_op.drop_column('avg_write_vs_edit_pct')
        batch_op.drop_column('avg_research_mutation_ratio')

    # ### end Alembic commands ###
