"""add context_growth_json to coding_session

Revision ID: a9f423e49825
Revises: de7d319b36e8
Create Date: 2026-04-08 19:02:42.345197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9f423e49825'
down_revision: Union[str, None] = 'de7d319b36e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_growth_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.drop_column('context_growth_json')

    # ### end Alembic commands ###
