"""add span_count and last_span_time for change detection

Revision ID: de6e4b7ef87f
Revises: 12a7671a4e5b
Create Date: 2026-04-08 14:59:28.033747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'de6e4b7ef87f'
down_revision: Union[str, None] = '12a7671a4e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('span_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_span_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.drop_column('last_span_time')
        batch_op.drop_column('span_count')

    # ### end Alembic commands ###
