"""add digest tables and analysis token tracking

Revision ID: de7d319b36e8
Revises: de6e4b7ef87f
Create Date: 2026-04-08 16:11:10.498496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'de7d319b36e8'
down_revision: Union[str, None] = 'de6e4b7ef87f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digest',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('stats_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('analysis_prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('analysis_completion_tokens', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPUTING_STATS', 'ANALYZING', 'COMPLETE', 'FAILED', name='digeststatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digest_project_name'), ['project_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_digest_user_id'), ['user_id'], unique=False)

    op.create_table('digest_section',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('digest_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section_type', sa.Enum('AT_A_GLANCE', 'WORK_AREAS', 'DEVELOPER_PERSONA', 'IMPRESSIVE_WINS', 'FRICTION_ANALYSIS', 'CLAUDE_MD_SUGGESTIONS', 'FEATURE_RECOMMENDATIONS', 'WORKFLOW_PATTERNS', 'AMBITIOUS_WORKFLOWS', 'FUN_ENDING', name='digestsectiontype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['digest_id'], ['digest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digest_section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digest_section_digest_id'), ['digest_id'], unique=False)

    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_prompt_tokens', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('analysis_completion_tokens', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.drop_column('analysis_completion_tokens')
        batch_op.drop_column('analysis_prompt_tokens')

    with op.batch_alter_table('digest_section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digest_section_digest_id'))

    op.drop_table('digest_section')
    with op.batch_alter_table('digest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digest_user_id'))
        batch_op.drop_index(batch_op.f('ix_digest_project_name'))

    op.drop_table('digest')
    # ### end Alembic commands ###
