"""initial schema

Revision ID: f536be249880
Revises: 
Create Date: 2026-04-22 12:01:21.474159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f536be249880'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_session',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('span_count', sa.Integer(), nullable=False),
    sa.Column('last_span_time', sa.DateTime(), nullable=True),
    sa.Column('context_growth_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('read_edit_ratio', sa.Float(), nullable=True),
    sa.Column('edits_without_read_pct', sa.Float(), nullable=True),
    sa.Column('research_mutation_ratio', sa.Float(), nullable=True),
    sa.Column('write_vs_edit_pct', sa.Float(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('repeated_edits_count', sa.Integer(), nullable=True),
    sa.Column('subagent_spawn_rate', sa.Float(), nullable=True),
    sa.Column('tokens_per_useful_edit', sa.Float(), nullable=True),
    sa.Column('context_pressure_score', sa.Float(), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=True),
    sa.Column('tool_calls_per_turn', sa.Float(), nullable=True),
    sa.Column('interrupt_count', sa.Integer(), nullable=True),
    sa.Column('agent_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('effort_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('adaptive_thinking_disabled', sa.Boolean(), nullable=True),
    sa.Column('interestingness_score', sa.Float(), nullable=True),
    sa.Column('skip_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_analysis_tokens', sa.Integer(), nullable=True),
    sa.Column('analysis_prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('analysis_completion_tokens', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INDEXED', 'PENDING', 'ANALYZED', 'FAILED', name='sessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coding_session_project_name'), ['project_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_coding_session_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coding_session_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coding_session_user_id'), ['user_id'], unique=False)

    op.create_table('digest',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('stats_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('analysis_prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('analysis_completion_tokens', sa.Integer(), nullable=False),
    sa.Column('analysis_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPUTING_STATS', 'ANALYZING', 'COMPLETE', 'FAILED', name='digeststatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digest_project_name'), ['project_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_digest_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_digest_user_id'), ['user_id'], unique=False)

    op.create_table('llm_call_log',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_kind', sa.Enum('SESSION_ANALYSIS', 'PROJECT_DETECTION', 'DIGEST_NARRATIVE', 'DIGEST_ACTIONS', 'DIGEST_FORWARD', name='llmcallkind'), nullable=False),
    sa.Column('scope_type', sa.Enum('SESSION', 'DIGEST', 'UNKNOWN', name='llmcallscopetype'), nullable=False),
    sa.Column('scope_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', name='llmcallstatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dollar_cost', sa.Float(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_call_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_call_log_call_kind'), ['call_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_log_scope_id'), ['scope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_log_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('refresh_run',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('command', sa.Enum('REFRESH', 'ANALYZE', 'DIGEST', name='refreshruncommand'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', name='refreshrunstatus'), nullable=False),
    sa.Column('sessions_analyzed', sa.Integer(), nullable=False),
    sa.Column('digests_generated', sa.Integer(), nullable=False),
    sa.Column('total_prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('total_completion_tokens', sa.Integer(), nullable=False),
    sa.Column('db_size_bytes', sa.Integer(), nullable=True),
    sa.Column('wall_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_run_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_run_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('scope_stats',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stats_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scope_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scope_stats_scope_type'), ['scope_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope_stats_scope_value'), ['scope_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope_stats_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('session_baseline',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('avg_turns', sa.Float(), nullable=False),
    sa.Column('avg_tool_count', sa.Float(), nullable=False),
    sa.Column('avg_read_edit_ratio', sa.Float(), nullable=False),
    sa.Column('avg_edits_without_read_pct', sa.Float(), nullable=False),
    sa.Column('avg_error_rate', sa.Float(), nullable=False),
    sa.Column('avg_duration_ms', sa.Float(), nullable=False),
    sa.Column('avg_research_mutation_ratio', sa.Float(), nullable=False),
    sa.Column('avg_write_vs_edit_pct', sa.Float(), nullable=False),
    sa.Column('tool_distribution_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_baseline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_baseline_project_name'), ['project_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_baseline_user_id'), ['user_id'], unique=False)

    op.create_table('session_daily_trend',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('indexed_count', sa.Integer(), nullable=False),
    sa.Column('analyzed_count', sa.Integer(), nullable=False),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('total_tool_calls', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('avg_read_edit_ratio', sa.Float(), nullable=True),
    sa.Column('avg_edits_without_read_pct', sa.Float(), nullable=True),
    sa.Column('avg_research_mutation_ratio', sa.Float(), nullable=True),
    sa.Column('avg_write_vs_edit_pct', sa.Float(), nullable=True),
    sa.Column('avg_error_rate', sa.Float(), nullable=True),
    sa.Column('avg_session_duration_ms', sa.Float(), nullable=True),
    sa.Column('avg_tool_calls_per_turn', sa.Float(), nullable=True),
    sa.Column('agent_distribution_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_daily_trend', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_daily_trend_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_daily_trend_project_name'), ['project_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_daily_trend_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_daily_trend_user_id'), ['user_id'], unique=False)

    op.create_table('digest_section',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('digest_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section_type', sa.Enum('AT_A_GLANCE', 'WORK_AREAS', 'DEVELOPER_PERSONA', 'IMPRESSIVE_WINS', 'FRICTION_ANALYSIS', 'CLAUDE_MD_SUGGESTIONS', 'FEATURE_RECOMMENDATIONS', 'RECOMMENDATIONS', 'WORKFLOW_PATTERNS', 'AMBITIOUS_WORKFLOWS', 'STOP_HOOK_SUGGESTIONS', 'FUN_ENDING', name='digestsectiontype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['digest_id'], ['digest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digest_section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digest_section_digest_id'), ['digest_id'], unique=False)

    op.create_table('insight',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('SUMMARY', 'FRICTION', 'WIN', 'RECOMMENDATION', 'PATTERN', 'SKILL_PROPOSAL', name='insightcategory'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='insightseverity'), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cluster_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['coding_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insight_cluster_label'), ['cluster_label'], unique=False)
        batch_op.create_index(batch_op.f('ix_insight_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_insight_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tool_call',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('span_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['coding_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_call', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_call_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_call_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_call_tool_name'), ['tool_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_call', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_call_tool_name'))
        batch_op.drop_index(batch_op.f('ix_tool_call_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tool_call_session_id'))

    op.drop_table('tool_call')
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insight_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_insight_session_id'))
        batch_op.drop_index(batch_op.f('ix_insight_cluster_label'))

    op.drop_table('insight')
    with op.batch_alter_table('digest_section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digest_section_digest_id'))

    op.drop_table('digest_section')
    with op.batch_alter_table('session_daily_trend', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_daily_trend_user_id'))
        batch_op.drop_index(batch_op.f('ix_session_daily_trend_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_session_daily_trend_project_name'))
        batch_op.drop_index(batch_op.f('ix_session_daily_trend_date'))

    op.drop_table('session_daily_trend')
    with op.batch_alter_table('session_baseline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_baseline_user_id'))
        batch_op.drop_index(batch_op.f('ix_session_baseline_project_name'))

    op.drop_table('session_baseline')
    with op.batch_alter_table('scope_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scope_stats_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_scope_stats_scope_value'))
        batch_op.drop_index(batch_op.f('ix_scope_stats_scope_type'))

    op.drop_table('scope_stats')
    with op.batch_alter_table('refresh_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_run_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_run_started_at'))

    op.drop_table('refresh_run')
    with op.batch_alter_table('llm_call_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_call_log_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_llm_call_log_scope_id'))
        batch_op.drop_index(batch_op.f('ix_llm_call_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_llm_call_log_call_kind'))

    op.drop_table('llm_call_log')
    with op.batch_alter_table('digest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digest_user_id'))
        batch_op.drop_index(batch_op.f('ix_digest_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_digest_project_name'))

    op.drop_table('digest')
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coding_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_coding_session_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_coding_session_session_id'))
        batch_op.drop_index(batch_op.f('ix_coding_session_project_name'))

    op.drop_table('coding_session')
    # ### end Alembic commands ###
