"""initial tables

Revision ID: fad81535b677
Revises: 
Create Date: 2026-04-07 20:51:14.204572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fad81535b677'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_session',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ANALYZED', 'FAILED', name='sessionstatus'), nullable=False),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coding_session_session_id'), ['session_id'], unique=False)

    op.create_table('insight',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('SUMMARY', 'FRICTION', 'WIN', 'RECOMMENDATION', 'PATTERN', 'SKILL_PROPOSAL', name='insightcategory'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='insightseverity'), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['coding_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insight_session_id'), ['session_id'], unique=False)

    op.create_table('tool_call',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('span_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['coding_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_call', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_call_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_call_tool_name'), ['tool_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_call', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_call_tool_name'))
        batch_op.drop_index(batch_op.f('ix_tool_call_session_id'))

    op.drop_table('tool_call')
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insight_session_id'))

    op.drop_table('insight')
    with op.batch_alter_table('coding_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coding_session_session_id'))

    op.drop_table('coding_session')
    # ### end Alembic commands ###
