"""add scope_stats table

Revision ID: fd9afcf347ac
Revises: 0d2b1bd6be0a
Create Date: 2026-04-21 15:43:24.299275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fd9afcf347ac'
down_revision: Union[str, None] = '0d2b1bd6be0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scope_stats',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stats_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scope_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scope_stats_scope_type'), ['scope_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope_stats_scope_value'), ['scope_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope_stats_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scope_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scope_stats_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_scope_stats_scope_value'))
        batch_op.drop_index(batch_op.f('ix_scope_stats_scope_type'))

    op.drop_table('scope_stats')
    # ### end Alembic commands ###
