"""add token efficiency signal columns

Revision ID: f305a74ff842
Revises: f536be249880
Create Date: 2026-04-23 15:22:55.732460

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f305a74ff842"
down_revision: str | None = "f536be249880"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("coding_session", schema=None) as batch_op:
        batch_op.add_column(sa.Column("error_retry_sequences", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("context_resets", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("duplicate_read_count", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("coding_session", schema=None) as batch_op:
        batch_op.drop_column("duplicate_read_count")
        batch_op.drop_column("context_resets")
        batch_op.drop_column("error_retry_sequences")

    # ### end Alembic commands ###
