"""add theme tables

Revision ID: ff7566b5e114
Revises: a1b2c3d4e5f6
Create Date: 2026-04-28 13:59:58.063056

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff7566b5e114"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "theme",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("task_count", sa.Integer(), nullable=False),
        sa.Column("first_date", sa.DateTime(), nullable=True),
        sa.Column("last_date", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("theme", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_theme_project_name"), ["project_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_theme_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "theme_task",
        sa.Column("theme_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.ForeignKeyConstraint(
            ["theme_id"],
            ["theme.id"],
        ),
        sa.PrimaryKeyConstraint("theme_id", "task_id"),
    )
    with op.batch_alter_table("theme_task", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_theme_task_tenant_id"), ["tenant_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("theme_task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_theme_task_tenant_id"))

    op.drop_table("theme_task")
    with op.batch_alter_table("theme", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_theme_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_theme_project_name"))

    op.drop_table("theme")
    # ### end Alembic commands ###
